name: ci-flow

on:
  pull_request:
  push:
    branches:
      - master
      - "releases/*"
    # tags-ignore:
    #   - "[0-9]+.[0-9]+.[0-9]+*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os.imageName }}
    strategy:
      matrix:
        rust_toolchain: ["stable"]
        os:
          - imageName: ubuntu-latest
            profile_rustup: default
          - imageName: "macOS-latest"
            profile_rustup: minimal
          - imageName: windows-latest
            profile_rustup: minimal
    env:
      CARGO_TERM_COLOR: always
      RUST_BACKTRACE: full
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust_toolchain }}
          override: true
          profile: ${{matrix.os.profile_rustup}}
      - uses: actions/checkout@v4
      - uses: mozilla-actions/sccache-action@v0.0.5
      - run: cargo clippy
      - run: cargo test
      - run: ${SCCACHE_PATH} --show-stats
        shell: bash
